### PR TITLE
Add ACS 2019 data to county_complete and add a new county_2019 data set

### PR DESCRIPTION
**Pull request by DavidDiez**
Please ignore that the branch is acs2017 (not acs2019). That was a mistake on my part. :)

Let me know if you have any questions, and feel free to make direct edits, of course. Thanks!

### CODE REVIEW

**Review by mine-cetinkaya-rundel — CHANGES_REQUESTED** [review]
Looks great, will you add a news entry to NEWS.md? Then I think it's ready to merge.

**Comment by DavidDiez** [comment]
Sigh... I've borked my session because I forgot to git pull before updating, and after a few rounds of trying to fix it, I haven't been able to (and don't have the time today to refamiliarize with Git to through it). Could you add the following lines to NEWS.md?

* Extended `county_complete` for new ACS 2019 data.
* Added a `county_2019` data set for many ACS 2019 variables.

**Comment by mine-cetinkaya-rundel** [comment]
No worries, I'll add in a bit!

**Comment by DavidDiez** [comment]
Thank you!! :)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Pull request merged**
